#!/bin/bash

intltool-extract --type=gettext/glade usr/share/live-installer/interface.ui
xgettext --language=Python --keyword=_ --keyword=N_ --output=live-installer.pot usr/lib/live-installer/installer.py usr/lib/live-installer/main.py usr/lib/live-installer/frontend/gtk_interface.py usr/lib/live-installer/partitioning.py usr/lib/live-installer/dialogs.py usr/share/live-installer/interface.ui.h
rm -f usr/share/live-installer/interface.ui.h
