#!/bin/bash

sudo rm -rf /etc/live-installer
sudo rm -rf /etc/init.d/live-installer
sudo rm -rf /usr/bin/live-installer
sudo rm -rf /usr/bin/live-installer-dm
sudo rm -rf /usr/lib/live-installer
sudo rm -rf /usr/share/live-installer
sudo rm -rf /usr/share/menu/live-installer
sudo rm -rf /usr/share/icons/live-installer.png
sudo rm -rf /usr/share/icons/live-installer.xpm
sudo rm -rf /usr/share/applications/live-installer-launcher.desktop
sudo rm -rf /usr/share/live-installer-slideshow

sudo cp -R usr /
sudo cp -R etc /
mkdir -p /usr/share/live-installer/slideshow/
sudo cp -R slideshow/{template.html,link,icons,en} /usr/share/live-installer/slideshow/
sudo cp -R slideshow/translated/* /usr/share/live-installer/slideshow/

live-installer --debug
